---
# handlers file for morpheus
- name: Morpheus Package Reconfigure
  block:
    - name: Running Morpheus Reconfigure on first host
      command: morpheus-ctl reconfigure
      when: inventory_hostname == play_hosts[0]

    - name: check URI
      uri:
        url: "https://{{ inventory_hostname }}/ping"
        return_content: true
      register: urlcontent
      until: '"MORPHEUS PING" in urlcontent.content'
      retries: 30
      delay: 30
      when: inventory_hostname == play_hosts[0]

    - name: Running Morpheus Reconfigure on the rest
      command: morpheus-ctl reconfigure
      when: inventory_hostname != play_hosts[0]

- name: Morpheus Config Change Reconfigure
  command: morpheus-ctl reconfigure